Name: vrpc-example
Environment: dev

RPC:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: vrpc.rpc
  ListenOn: 127.0.0.1:8080
  Timeout: 5000

VRPC:
  Request:
    Topic: request-topic
    Kafka:
      Brokers:
        - localhost:9092
      Group: vrpc-request-group
  Respond:
    Topic: response-topic
    Kafka:
      Brokers:
        - localhost:9092
      Group: vrpc-response-group
  Timeout: 5000

Kafka:
  Brokers:
    - localhost:9092
  Group: vrpc-group
  Topic: vrpc-topic

Server:
  Name: vrpc-example-server