// protoc --go_out=. codec.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/codec/codec.proto

package codec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                      // 消息唯一ID
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`                                                                             // 服务名称
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                                                                               // 方法名称
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // 序列化后的请求参数
	Metadata      map[string]*StringList `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据（string -> []string）
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_internal_codec_codec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Base) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Base) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Base) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Base) GetMetadata() map[string]*StringList {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Base) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_internal_codec_codec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// Request 请求消息结构
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_codec_codec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

// Response 响应消息结构
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 状态码
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`    // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_codec_codec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_codec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_codec_codec_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_codec_codec_proto protoreflect.FileDescriptor

const file_internal_codec_codec_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/codec/codec.proto\x12\x04vrpc\"\x85\x02\n" +
	"\x04Base\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x124\n" +
	"\bmetadata\x18\x05 \x03(\v2\x18.vrpc.Base.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x1aM\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.vrpc.StringListR\x05value:\x028\x01\"\"\n" +
	"\n" +
	"StringList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\")\n" +
	"\aRequest\x12\x1e\n" +
	"\x04base\x18\x01 \x01(\v2\n" +
	".vrpc.BaseR\x04base\"X\n" +
	"\bResponse\x12\x1e\n" +
	"\x04base\x18\x01 \x01(\v2\n" +
	".vrpc.BaseR\x04base\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB\n" +
	"Z\b./;codecb\x06proto3"

var (
	file_internal_codec_codec_proto_rawDescOnce sync.Once
	file_internal_codec_codec_proto_rawDescData []byte
)

func file_internal_codec_codec_proto_rawDescGZIP() []byte {
	file_internal_codec_codec_proto_rawDescOnce.Do(func() {
		file_internal_codec_codec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_codec_codec_proto_rawDesc), len(file_internal_codec_codec_proto_rawDesc)))
	})
	return file_internal_codec_codec_proto_rawDescData
}

var file_internal_codec_codec_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_codec_codec_proto_goTypes = []any{
	(*Base)(nil),       // 0: vrpc.Base
	(*StringList)(nil), // 1: vrpc.StringList
	(*Request)(nil),    // 2: vrpc.Request
	(*Response)(nil),   // 3: vrpc.Response
	nil,                // 4: vrpc.Base.MetadataEntry
}
var file_internal_codec_codec_proto_depIdxs = []int32{
	4, // 0: vrpc.Base.metadata:type_name -> vrpc.Base.MetadataEntry
	0, // 1: vrpc.Request.base:type_name -> vrpc.Base
	0, // 2: vrpc.Response.base:type_name -> vrpc.Base
	1, // 3: vrpc.Base.MetadataEntry.value:type_name -> vrpc.StringList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_codec_codec_proto_init() }
func file_internal_codec_codec_proto_init() {
	if File_internal_codec_codec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_codec_codec_proto_rawDesc), len(file_internal_codec_codec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_codec_codec_proto_goTypes,
		DependencyIndexes: file_internal_codec_codec_proto_depIdxs,
		MessageInfos:      file_internal_codec_codec_proto_msgTypes,
	}.Build()
	File_internal_codec_codec_proto = out.File
	file_internal_codec_codec_proto_goTypes = nil
	file_internal_codec_codec_proto_depIdxs = nil
}
