# config/vrpc.yaml
mq:
  type: kafka
  brokers:
    - localhost:9092
  topic: vrpc
  settings:
    compression: gzip
    batch_size: 100
    linger_ms: 10

timeout:
  request: 30s
  connect: 5s

retry:
  count: 3
  interval: 100ms

debug: true