// protoc --go_out=. vrpc.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: vrpc.proto

package vrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []*Input_Row           `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_vrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_vrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_vrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetRow() []*Input_Row {
	if x != nil {
		return x.Row
	}
	return nil
}

type Input_Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input_Row) Reset() {
	*x = Input_Row{}
	mi := &file_vrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input_Row) ProtoMessage() {}

func (x *Input_Row) ProtoReflect() protoreflect.Message {
	mi := &file_vrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input_Row.ProtoReflect.Descriptor instead.
func (*Input_Row) Descriptor() ([]byte, []int) {
	return file_vrpc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Input_Row) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_vrpc_proto protoreflect.FileDescriptor

const file_vrpc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"vrpc.proto\x12\x04vrpc\"E\n" +
	"\x05Input\x12!\n" +
	"\x03row\x18\x01 \x03(\v2\x0f.vrpc.Input.RowR\x03row\x1a\x19\n" +
	"\x03Row\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB\tZ\a./;vrpcb\x06proto3"

var (
	file_vrpc_proto_rawDescOnce sync.Once
	file_vrpc_proto_rawDescData []byte
)

func file_vrpc_proto_rawDescGZIP() []byte {
	file_vrpc_proto_rawDescOnce.Do(func() {
		file_vrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vrpc_proto_rawDesc), len(file_vrpc_proto_rawDesc)))
	})
	return file_vrpc_proto_rawDescData
}

var file_vrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vrpc_proto_goTypes = []any{
	(*Input)(nil),     // 0: vrpc.Input
	(*Input_Row)(nil), // 1: vrpc.Input.Row
}
var file_vrpc_proto_depIdxs = []int32{
	1, // 0: vrpc.Input.row:type_name -> vrpc.Input.Row
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vrpc_proto_init() }
func file_vrpc_proto_init() {
	if File_vrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vrpc_proto_rawDesc), len(file_vrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vrpc_proto_goTypes,
		DependencyIndexes: file_vrpc_proto_depIdxs,
		MessageInfos:      file_vrpc_proto_msgTypes,
	}.Build()
	File_vrpc_proto = out.File
	file_vrpc_proto_goTypes = nil
	file_vrpc_proto_depIdxs = nil
}
