// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: nextcfg.proto

package nextcfgclient

import (
	"context"
	"github.com/nextpkg/vrpc/example/nextcfg"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = nextcfg.Request
	Response = nextcfg.Response

	Nextcfg interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultNextcfg struct {
		cli zrpc.Client
	}
)

func NewNextcfg(cli zrpc.Client) Nextcfg {
	return &defaultNextcfg{
		cli: cli,
	}
}

func (m *defaultNextcfg) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := nextcfg.NewNextcfgClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
