// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: nextcfg.proto

package nextcfg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nextcfg_Ping_FullMethodName = "/nextcfg.Nextcfg/Ping"
)

// NextcfgClient is the client API for Nextcfg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NextcfgClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type nextcfgClient struct {
	cc grpc.ClientConnInterface
}

func NewNextcfgClient(cc grpc.ClientConnInterface) NextcfgClient {
	return &nextcfgClient{cc}
}

func (c *nextcfgClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Nextcfg_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NextcfgServer is the server API for Nextcfg service.
// All implementations must embed UnimplementedNextcfgServer
// for forward compatibility.
type NextcfgServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedNextcfgServer()
}

// UnimplementedNextcfgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNextcfgServer struct{}

func (UnimplementedNextcfgServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNextcfgServer) mustEmbedUnimplementedNextcfgServer() {}
func (UnimplementedNextcfgServer) testEmbeddedByValue()                 {}

// UnsafeNextcfgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NextcfgServer will
// result in compilation errors.
type UnsafeNextcfgServer interface {
	mustEmbedUnimplementedNextcfgServer()
}

func RegisterNextcfgServer(s grpc.ServiceRegistrar, srv NextcfgServer) {
	// If the following call pancis, it indicates UnimplementedNextcfgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nextcfg_ServiceDesc, srv)
}

func _Nextcfg_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NextcfgServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nextcfg_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NextcfgServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Nextcfg_ServiceDesc is the grpc.ServiceDesc for Nextcfg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nextcfg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nextcfg.Nextcfg",
	HandlerType: (*NextcfgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Nextcfg_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nextcfg.proto",
}
